FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./package.json ./package.json

COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json 

RUN bun install

COPY ./apps/backend ./apps/backend

COPY . .


RUN bun run db:generate

EXPOSE 8080

CMD ["bun", "run", "start:backend"]