FROM oven/bun:1

WORKDIR /usr/src/app


COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json 

RUN bun install

COPY ./packages ./packages

COPY ./apps/backend ./apps/backend

COPY . .

RUN bun run db:generate

EXPOSE 8080

CMD ["bun", "run", "start:backend"]