name: backend deploy
on:
  push:
    branches: [main]
    paths:
      - "apps/backend/**"
      - ".github/workflows/cd_backend.yml"
      - "Docker/Dockerfile.backend"
      - "package.json"
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push the backend Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Docker/Dockerfile.backend
          push: true
          tags: partha978/monorepo-deploy-to-vm:${{ github.sha }}